#!/bin/sh

case "$1" in
	start)
		echo "Starting simple server"
		start-stop-daemon -S -n simpleserver /usr/bin/aesdsocket -- -d
		;;
	stop)
		echo "Stoping simple server"
		start-stop-daemon -K -n simpleserver
		;;
	*)
		echo "Usage: $0 {start|stop}"
     		exit 1
 esac
 
 exit 0
